#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DiscoveryRpcServiceManifest {
    pub schema_version: u16,
    pub kind: &'static str,
    pub domain: &'static str,
    pub capability: &'static str,
    pub sdk_family: &'static str,
    pub proto_roots: Vec<&'static str>,
    pub methods: Vec<DiscoveryRpcMethod>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DiscoveryRpcMethod {
    pub package: &'static str,
    pub service: &'static str,
    pub surface: &'static str,
    pub method: &'static str,
    pub operation_id: &'static str,
    pub auth: &'static str,
    pub idempotency: &'static str,
    pub streaming: &'static str,
    pub owner: &'static str,
    pub compatibility: &'static str,
}

struct MethodSpec {
    package: &'static str,
    service: &'static str,
    surface: &'static str,
    method: &'static str,
    operation_id: &'static str,
    auth: &'static str,
    idempotency: &'static str,
    streaming: &'static str,
}

pub fn discovery_rpc_service_manifest() -> DiscoveryRpcServiceManifest {
    DiscoveryRpcServiceManifest {
        schema_version: 1,
        kind: "sdkwork.rpc.manifest",
        domain: "platform",
        capability: "discovery",
        sdk_family: "sdkwork-discovery-rpc-sdk",
        proto_roots: vec!["../../proto"],
        methods: vec![
            method(MethodSpec {
                package: "sdkwork.discovery.internal.v1",
                service: "RegistryService",
                surface: "internal",
                method: "RegisterInstance",
                operation_id: "discovery.registry.instances.register",
                auth: "service-identity",
                idempotency: "optional",
                streaming: "unary",
            }),
            method(MethodSpec {
                package: "sdkwork.discovery.internal.v1",
                service: "RegistryService",
                surface: "internal",
                method: "BatchRegisterInstances",
                operation_id: "discovery.registry.instances.batch_register",
                auth: "service-identity",
                idempotency: "optional",
                streaming: "unary",
            }),
            method(MethodSpec {
                package: "sdkwork.discovery.internal.v1",
                service: "RegistryService",
                surface: "internal",
                method: "RenewLease",
                operation_id: "discovery.registry.leases.renew",
                auth: "service-identity",
                idempotency: "optional",
                streaming: "unary",
            }),
            method(MethodSpec {
                package: "sdkwork.discovery.internal.v1",
                service: "RegistryService",
                surface: "internal",
                method: "DeregisterInstance",
                operation_id: "discovery.registry.instances.deregister",
                auth: "service-identity",
                idempotency: "optional",
                streaming: "unary",
            }),
            method(MethodSpec {
                package: "sdkwork.discovery.internal.v1",
                service: "RegistryService",
                surface: "internal",
                method: "ReportInstanceStatus",
                operation_id: "discovery.registry.instances.status.report",
                auth: "service-identity",
                idempotency: "optional",
                streaming: "unary",
            }),
            method(MethodSpec {
                package: "sdkwork.discovery.internal.v1",
                service: "RegistryService",
                surface: "internal",
                method: "RetrieveInstance",
                operation_id: "discovery.registry.instances.retrieve",
                auth: "service-identity",
                idempotency: "none",
                streaming: "unary",
            }),
            method(MethodSpec {
                package: "sdkwork.discovery.internal.v1",
                service: "RegistryService",
                surface: "internal",
                method: "DiscoverInstances",
                operation_id: "discovery.registry.instances.discover",
                auth: "service-identity",
                idempotency: "none",
                streaming: "unary",
            }),
            method(MethodSpec {
                package: "sdkwork.discovery.internal.v1",
                service: "DiscoveryConfigService",
                surface: "internal",
                method: "RetrieveEffectiveConfig",
                operation_id: "discovery.config.effective.retrieve",
                auth: "service-identity",
                idempotency: "none",
                streaming: "unary",
            }),
            method(MethodSpec {
                package: "sdkwork.discovery.internal.v1",
                service: "DiscoveryConfigService",
                surface: "internal",
                method: "WatchConfig",
                operation_id: "discovery.config.releases.watch",
                auth: "service-identity",
                idempotency: "none",
                streaming: "server",
            }),
            method(MethodSpec {
                package: "sdkwork.discovery.internal.v1",
                service: "DiscoveryWatchService",
                surface: "internal",
                method: "WatchService",
                operation_id: "discovery.registry.services.watch",
                auth: "service-identity",
                idempotency: "none",
                streaming: "server",
            }),
            method(MethodSpec {
                package: "sdkwork.discovery.backend.v3",
                service: "DiscoveryAdminService",
                surface: "backend",
                method: "CreateConfigDraft",
                operation_id: "discovery.config.drafts.create",
                auth: "backend-operator",
                idempotency: "required",
                streaming: "unary",
            }),
            method(MethodSpec {
                package: "sdkwork.discovery.backend.v3",
                service: "DiscoveryAdminService",
                surface: "backend",
                method: "PublishConfig",
                operation_id: "discovery.config.releases.publish",
                auth: "backend-operator",
                idempotency: "required",
                streaming: "unary",
            }),
            method(MethodSpec {
                package: "sdkwork.discovery.backend.v3",
                service: "DiscoveryAdminService",
                surface: "backend",
                method: "RollbackConfig",
                operation_id: "discovery.config.releases.rollback",
                auth: "backend-operator",
                idempotency: "required",
                streaming: "unary",
            }),
            method(MethodSpec {
                package: "sdkwork.discovery.backend.v3",
                service: "DiscoveryAdminService",
                surface: "backend",
                method: "ListServices",
                operation_id: "discovery.registry.services.list",
                auth: "backend-operator",
                idempotency: "none",
                streaming: "unary",
            }),
        ],
    }
}

fn method(spec: MethodSpec) -> DiscoveryRpcMethod {
    DiscoveryRpcMethod {
        package: spec.package,
        service: spec.service,
        surface: spec.surface,
        method: spec.method,
        operation_id: spec.operation_id,
        auth: spec.auth,
        idempotency: spec.idempotency,
        streaming: spec.streaming,
        owner: "sdkwork-platform",
        compatibility: "stable",
    }
}
