[package]
name = "sdkwork-discovery-storage-memory"
edition.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
sdkwork-discovery-contract.workspace = true
sdkwork-discovery-storage-contract.workspace = true
sha2.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true
